apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "postgres-app"
        vault.hashicorp.com/agent-inject-secret-database-config: "internal/database/config"
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{ with secret "internal/database/config" -}}
          POSTGRES_USER={{ .Data.data.POSTGRES_USER }}
          POSTGRES_PASSWORD={{ .Data.data.POSTGRES_PASSWORD }}
          POSTGRES_DB={{ .Data.data.POSTGRES_DB }}
          {{- end }}
    spec:
      serviceAccountName: postgres-app
      containers:
        - name: postgres-db
          image: postgres:14-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-cred
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cred
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-cred
                  key: POSTGRES_DB
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          # command: ["/bin/bash", "-c"]
          # args:
          #   ['source /vault/secrets/database-config && env > /vault/secrets/db && tail -f /dev/null']
          imagePullPolicy: "Always"
          ports:
            - name: postgres-port
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-database"
