apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-app
  namespace: postgres
---
apiVersion: v1
kind: Secret
metadata:
 name: postgres-app-secret
 namespace: postgres
 annotations:
   kubernetes.io/service-account.name: postgres-app
type: kubernetes.io/service-account-token
---
# new
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
# new
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
  - kind: ServiceAccount
    name: postgres-app
    namespace: postgres