# Default values for postgresql-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: postgres
  tag: 14-alpine
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  